[2019-04-18 15:20:41,397]-[ERROR]-[my_log.py]-[python1]-[日志信息]：糟糕的结果
[2019-04-18 15:58:22,414]-[ERROR]-[my_log.py]-[python1]-[日志信息]：糟糕的结果
[2019-04-18 16:00:11,282]-[ERROR]-[my_log.py]-[python1]-[日志信息]：糟糕的结果
[2019-04-18 16:00:48,067]-[ERROR]-[my_log.py]-[python1]-[日志信息]：糟糕的结果
[2019-04-18 16:02:31,275]-[ERROR]-[my_log.py]-[python1]-[日志信息]：糟糕的结果
[2019-04-18 16:02:41,506]-[ERROR]-[my_log.py]-[python1]-[日志信息]：糟糕的结果
[2019-04-18 17:30:15,236]-[ERROR]-[my_log.py]-[python1]-[日志信息]：糟糕的结果
